### ISSUE TITLE
Browser Issue (Safari 14): Gap missing between Powerful and empowering section columns

### ISSUE THREAD

**Issue by robinwpdeveloper** [WordPress/wporg-main-2022#109] opened 2022-08-30 02:52 UTC
**Describe the bug**
Spacing missing for the old safari versions (14 or less).
Powerful and empowering section columns are having no spacing in between.

**To Reproduce**
1. Go to https://wordpress.org/#benefits
2. You'll see Powerful and empowering section columns are having no gap.

**Expected behavior**
Powerful and empowering section columns are having gap in other browsers or safari latest browsers. but no gap for safari 14 or less.

**Screenshots**
<img width="1233" alt="Screen Shot 2022-08-30 at 8 29 30 AM" src="https://user-images.githubusercontent.com/86726198/187337608-b8bf3bd1-7e81-4af2-87a4-20698cbd5198.png">

**Desktop (please complete the following information):**
 - OS: iOS 
 - Browser safari
 - Version 14

**Comment by hz-tyfoon** [comment] 2022-08-30 05:42
Thanks @robinwpdeveloper for the issue.
I've checked & can confirm it exist in safari 14. 

I've had a chance to investigate the issue & so far looks to me the issue is coming from 'columns block'.  'columns block' use `flex gap` which isn't supported in safari 14.

the 100px gap coming from `.wp-block-columns.wp-container-17, .wp-block-columns.wp-container-28` selector's css.

screenshot:
![Screenshot at Aug 30 11-18-16](https://user-images.githubusercontent.com/59374562/187355483-52c550d7-e7f6-4ea4-9442-af0859b23e4c.png)

So, May be there can be a workaround by using **lobotomized owl** trick. 

I mean, in this case: instead of using 
`gap: 100px;` on `.wp-block-columns.wp-container-17, .wp-block-columns.wp-container-28` selector, 

we on can use 
`margin-left: 100px;` on `.wp-block-columns.wp-container-17 > * + *, .wp-block-columns.wp-container-28 > * + *` selector.

This seems to be working perfectly.

screenshot:
![Screenshot at Aug 30 11-36-44](https://user-images.githubusercontent.com/59374562/187357856-77b9459f-ab0c-4844-905e-9b064b5fac8c.png)

**Comment by ryelle** [comment] 2022-08-30 20:08
When you add the margin like that, the columns are no longer equal widths, so that's not an ideal solution. Additionally, the CSS here is generated by the core Columns block, and we can't know that the space will always be 100px (here it is, but on other pages we might have 3 columns with 60px spacing, for example).

Since this is still technically readable, and Safari 14.1/iOS 14.5 (released in April 2021) supports `gap` in flex, I'm inclined to leave this as is. ~I'll leave this open for other opinions though.~

**Closed as not planned** 2022-10-03 17:40 UTC
Labels: [Type] Bug, [Component] Theme, Browser Support, [Status] In Discussion
