### ISSUE TITLE
Installing font error

### ISSUE THREAD

**Issue by farhadsakhaei** [WordPress/wporg-main-2022#388] opened 2024-02-11 13:36 UTC
**Describe the bug**

When we want to install or upload a font, we get the following error:
No font faces were installed. Fetch error: امکان ایجاد شاخه wp-content/fonts/sites/60 نیست. آیا شاخه مادر آن با سرور قابل نوشتن است؟

That means there is a problem with creating/writing on the path: wp-content/fonts/sites/60
Site: fa.wordpress.org

Appreciate for any help

**Comment by dd32** [comment] 2024-02-12 01:36
Hi,

WordPress.org does not currently support Font installations.

It's not clear if we'll enable support for this either, as historically we haven't added custom fonts for `fa` despite multiple requests: https://meta.trac.wordpress.org/ticket/3933

I'm going to close this as a duplicate of the above ticket, as this isn't exactly something wrong with the theme and rather that the feature doesn't work on WordPress.org (and again, I'm not sure we'd want it to).

**Closed as not planned by dd32** 2024-02-12 01:36 UTC

**Comment by farhadsakhaei** [comment] 2024-02-12 07:11
@dd32 
Hi,
Thank you for your reply,
We really need a better font, The fa.wp.org is actually ugly by current fonts
As you can see in that ticket, there are many people are watching and following this topic
I don't know how we can make this topic more important for Persian language
Appreciate for any help
