### ISSUE TITLE
Arrow in CTA links is converted to emoji

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#30] opened 2022-07-28 17:12 UTC
In some links (the CTA style text links), the link text includes an arrow icon. The mockup uses the `↗` character, but on the staging site WordPress is converting it to ↗️  (oops, so does github).

| Mockup | Staging site |
|---------|---------|
| <img width="293" alt="" src="https://user-images.githubusercontent.com/541093/181596539-095a982a-0f90-43d2-9964-198dee60a40f.png"> | <img width="212" alt="" src="https://user-images.githubusercontent.com/541093/181597288-891c493a-8dff-48fd-9986-198c4dc7791d.png"> |

It would be best if we could use the arrow character itself so it can respond to any link color.

**Comment by dd32** [comment] 2022-08-01 03:42
The WordPress emoji converter [will ignore any elements with the `wp-exclude-emoji` class](https://github.com/WordPress/wordpress-develop/blob/trunk/src/js/_enqueues/wp/emoji.js#L148-L157), however setting the class on either the `<a>`, `<p>`, or even the cover block, it isn't working as intended in my testing.

**Comment by dd32** [comment] 2022-08-01 04:17
Unfortunately, I believe we'll have to disable the emoji replacement entirely if we wish to use this character (Or insert it after DOMContentLoaded).

See https://core.trac.wordpress.org/ticket/52219 for the upstream bug of why `wp-exclude-emoji` doesn't work here.

**Comment by azaozz** [comment] 2022-08-02 00:46
Would it be possible to append the "Unicode Character 'VARIATION SELECTOR-15' (U+FE0E)" to that arrow? This is the official way to specify display variations, see: http://unicode.org/emoji/charts/emoji-variants.html. 

In twemoji that char is used to prevent replacement with an image, see https://github.com/twitter/twemoji/blob/gh-pages/twemoji.js#L203-L206.

I know, not particularly convenient but not seeing anything else that can fix this at the moment.

**Comment by dd32** [comment] 2022-08-02 00:59
Thank you @azaozz!

I think suffixing that extra character in the copy will do for now - it's not the best option from an editing point-of-view, and might have issues with translation, but it's at least an option that doesn't require disabling emoji fallback entirely (Which we might still want to consider)

**Comment by dd32** [comment] 2022-08-02 01:08
I've appended `&#65038;` in the HTML view to the arrow emoji.. The entity then vanished - it appears that it's been merged into the arrow character, as it's no longer being converted by twemoji as anticipated! 🎉

**Comment by ryelle** [comment] 2022-08-02 19:58
Can we filter the content to add that? so editors don't need to worry about it (and maybe it won't get sent to translators). Probably would need both to add the character to both upper-right and upper-left for eventual RTL support.

**Comment by azaozz** [comment] 2022-08-02 20:02
Yeah, probably can. But thinking it would be better to tweak/fix the JS and add these there. It would be much easier to find emojis in elements that have the `wp-exclude-emoji` class.

**Comment by ryelle** [comment] 2022-08-02 20:18
Fixing the JS would be a core fix though, right? I was asking about a filter so that we can use the arrow on the w.org site now, while waiting for the core fix.

**Comment by azaozz** [comment] 2022-08-02 22:52
Yep, you're right. My mindset is to see everything as a core bug that needs fixing, but it makes sense to patch it here in the meantime. A PHP filter would work as long as all arrow emoji are "patched". Otherwise better to do that from JS. Something like this perhaps (example code):
```
( function() {
const emojiRegex = // copy the big emoji matching regex from twemoji

document.querySelectorAll( '.wp-exclude-emoji' ).forEach( ( element ) => {
    if ( element.textContent ) {
        element.textContent = element.textContent.replace( emojiRegex, ( emoji ) => emoji.concat( \uFE0E ) );
    }
} );
}();
```

**Closed as completed** 2022-08-04 16:33 UTC
Labels: [Component] Backend
