### ISSUE TITLE
Social media logo for “x” is wrong

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/wporg-main-2022#331] opened 2023-10-13 00:35 UTC
In the social media logos on the bottom of the site, it still has the bird for the site formerly known as Twitter.

**Comment by adamwoodnz** [comment] 2023-10-13 02:01
Thanks for reporting, duplicate of https://github.com/WordPress/wporg-mu-plugins/issues/470

**Closed as completed by adamwoodnz** 2023-10-13 02:01 UTC
