### ISSUE TITLE
Community image on mobile is blurry

### ISSUE THREAD

**Issue by annezazu** [WordPress/wporg-main-2022#90] opened 2022-08-16 21:02 UTC
**Describe the bug**

Community photo is blurry on mobile

**To Reproduce**
View homepage on mobile device (iphone SE2) and see community section

**Screenshots**
![IMG_2079](https://user-images.githubusercontent.com/26996883/184984672-ad5f9397-6989-44e7-9dc8-fc6416c8d381.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2
 - Browser: Safari

**Comment by ryelle** [comment] 2022-08-16 21:34
I can reproduce this in Chrome's mobile preview.

This might be fixed by #89, since we're swapping out this image for a higher-resolution version.

**Comment by ryelle** [comment] 2022-08-17 15:53
Looks like this was fixed by #89.

**Closed as completed by ryelle** 2022-08-17 15:53 UTC
Labels: [Type] Bug, [Component] Content
